-- Seed de testimonios (datos iniciales desde Success.tsx + patrón doc)
-- Ejecutar después de aplicar 001_testimonials.sql en el proyecto Supabase.

INSERT INTO public.testimonials (
  name,
  country,
  role,
  area,
  program,
  quote,
  timeline,
  status_label,
  media_type,
  photo_url,
  video_url,
  category,
  sort_order
) VALUES
(
  'Ricardo Ochoa',
  'Colombia',
  'Profesional',
  'Consultoría',
  NULL,
  'La confianza que brinda Ivon y su equipo, además de su experiencia en EB-2 NIW, fue lo que más me impactó. Afiancé que puedo aportar mucho al progreso de EE.UU.',
  'Aprobado en 120 días',
  NULL,
  'text_photo',
  '/testimonials/ricardo-ochoa.jpg',
  NULL,
  'aprobados_abogada_marcela_rodriguez',
  0
),
(
  'Carlos M.',
  NULL,
  'Ingeniero de Software',
  'STEM & Tecnología',
  NULL,
  'MORE transformó mi perfil en una narrativa de impacto nacional. En 4 meses tenía mi aprobación. El proceso fue claro y estratégico desde el día uno.',
  'Aprobado en 120 días',
  NULL,
  'text_photo',
  NULL,
  NULL,
  'aprobados_abogada_marcela_rodriguez',
  1
),
(
  'Dra. María L.',
  NULL,
  'Médica Investigadora',
  'Salud & Medicina',
  NULL,
  'El equipo me ayudó a construir un plan profesional que demostró mi impacto en salud pública de manera contundente.',
  'Aprobada en 95 días',
  NULL,
  'text_photo',
  NULL,
  NULL,
  'aprobados_abogada_marcela_rodriguez',
  2
),
(
  'Roberto S.',
  NULL,
  'Emprendedor Social',
  'Negocios & Impacto',
  NULL,
  'Sin oferta de empleo, pensé que era imposible. MORE demostró que mi trayectoria empresarial era suficiente para la EB-2 NIW.',
  'Aprobado en 140 días',
  NULL,
  'text_photo',
  NULL,
  NULL,
  'aprobados_abogada_marcela_rodriguez',
  3
),
(
  'Yalile P',
  'Colombia',
  'Odontóloga',
  NULL,
  'Unsung Professional Program – Plan Acelerador',
  'Ivon, que felicidad! gracias, gracias porque siempre creíste en cada uno de nosotros porque siempre nos animaste a que no desfalleciéramos y a pensar en que si podría ser posible y bueno esta es la prueba que hoy Dios nos da con esta aprobación, estamos felices! Te agradezco inmensamente todo. Gracias gracias gracias',
  '87 días',
  'APROBADO INHOUSE',
  'text_photo',
  NULL,
  NULL,
  'abogados_in_house',
  0
),
(
  'Jose Reyes',
  'República Dominicana',
  'Ingeniero de Sistemas',
  NULL,
  'Unsung Professional Program – Plan Acelerador',
  'Quiero expresar mi más sincero agradecimiento al equipo de More por el acompañamiento brindado en mi proyecto de Visa EB-2 por Interés Nacional. Durante todo el proceso, he podido constatar su alto nivel de profesionalismo, organización y compromiso. No solo cuentan con una estructura técnica sólida, sino también con un gran equipo humano, caracterizado por la excelencia, la ética y la dedicación genuina hacia cada proyecto que asumen. Su orientación estratégica, claridad en cada paso y enfoque meticuloso han generado confianza y seguridad en un proceso tan importante como este. Deposito del proyecto 05/08/2024 y recibimos la aprobación 12/09/2024. Gracias por su excelencia y por el valor humano que demuestran en cada etapa del proceso.',
  '38 días',
  'APROBADO INHOUSE',
  'text_photo',
  NULL,
  NULL,
  'abogados_in_house',
  1
),
(
  'Piedad Salamanca',
  'Colombia',
  'Comunicadora Social',
  NULL,
  'Unsung Professional Program – Plan Acelerador',
  'Quiero expresar mi más sincero agradecimiento al equipo MORE por su acompañamiento experto, riguroso y humano durante mi proceso de visa EB-2 NIW. Su profesionalismo, claridad estratégica y compromiso permanente hicieron que cada etapa se sintiera estructurada, sólida y confiable. Más que un servicio, encontré un equipo que entiende los sueños, respalda las trayectorias y trabaja con excelencia para convertir proyectos de vida en realidades posibles. Gracias por caminar este proceso conmigo.',
  NULL,
  'En espera de aprobación',
  'text_photo',
  NULL,
  NULL,
  'en_espera_aprobacion',
  0
)
;
